#!/usr/bin/env bash
set -euo pipefail

TARGETS="claude,codex,cursor"

usage() {
  cat <<'USAGE'
Usage: configure-apm-agent-support.sh [--targets claude,codex,cursor]

Updates repository-local configuration for generated APM install assets:
- initializes apm.yml when the repository does not have one;
- ensures apm.yml contains the requested targets;
- marks generated agent assets as linguist-generated in .gitattributes;
- excludes generated agent assets from Super-Linter through FILTER_REGEX_EXCLUDE.

Add copilot only when the repository intentionally commits GitHub Copilot
instructions generated by APM.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --targets)
      if [ "$#" -lt 2 ]; then
        echo "--targets requires a value" >&2
        exit 2
      fi
      TARGETS="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [ -z "$TARGETS" ]; then
  echo "--targets must not be empty" >&2
  exit 2
fi

IFS=',' read -r -a TARGET_ARRAY <<< "$TARGETS"
for target in "${TARGET_ARRAY[@]}"; do
  case "$target" in
    claude|codex|cursor|copilot|gemini|opencode|antigravity) ;;
    intellij|kiro|vscode|windsurf) ;;
    *)
      echo "Unsupported target: $target" >&2
      exit 2
      ;;
  esac
done

has_target() {
  local needle="$1"
  local target
  for target in "${TARGET_ARRAY[@]}"; do
    [ "$target" = "$needle" ] && return 0
  done
  return 1
}

make_tmp_file() {
  mktemp "${TMPDIR:-/tmp}/configure-apm-agent-support.XXXXXX"
}

ensure_line() {
  local file="$1"
  local line="$2"
  touch "$file"
  grep -Fxq "$line" "$file" || printf '%s\n' "$line" >> "$file"
}

initialize_apm_project() {
  if [ -f apm.yml ]; then
    return 0
  fi

  command -v apm >/dev/null 2>&1 || {
    echo "apm CLI is required to initialize apm.yml" >&2
    exit 1
  }

  apm init -y --target "$TARGETS"
}

update_targets() {
  local tmp
  tmp="$(make_tmp_file)"

  local output_lines=()
  if [ -f apm.yml ]; then
    local skip_targets_block=0
    local line
    while IFS= read -r line || [ -n "$line" ]; do
      case "$line" in
        '# Which agent platforms to deploy to.') continue ;;
        '# Resolution order: --target flag > this field > auto-detect from filesystem.') continue ;;
        '# Accepted values:') continue ;;
        '# gemini, antigravity,'*) continue ;;
      esac

      if [[ "$line" =~ ^targets:[[:space:]]*$ ]]; then
        skip_targets_block=1
        continue
      fi

      if [[ "$line" =~ ^[^[:space:]#][^:]*: ]]; then
        skip_targets_block=0
      fi

      if [ "$skip_targets_block" -eq 0 ]; then
        output_lines[${#output_lines[@]}]="$line"
      fi
    done < apm.yml
  fi

  while [ "${#output_lines[@]}" -gt 0 ]; do
    local last_index=$((${#output_lines[@]} - 1))
    [ -n "${output_lines[$last_index]}" ] && break
    unset "output_lines[$last_index]"
  done

  if [ "${#output_lines[@]}" -gt 0 ]; then
    printf '%s\n' "${output_lines[@]}" >> "$tmp"
    printf '\n' >> "$tmp"
  fi
  printf 'targets:\n' >> "$tmp"
  for target in "${TARGET_ARRAY[@]}"; do
    printf '  - %s\n' "$target" >> "$tmp"
  done

  mv "$tmp" apm.yml
}

update_gitattributes() {
  ensure_line .gitattributes '/.agents/** linguist-generated=true'

  if has_target codex; then
    ensure_line .gitattributes '/.codex/** linguist-generated=true'
  fi

  if has_target claude; then
    ensure_line .gitattributes '/.claude/apm-hooks.json linguist-generated=true'
    ensure_line .gitattributes '/.claude/settings.json linguist-generated=true'
    ensure_line .gitattributes '/.claude/rules/** linguist-generated=true'
    ensure_line .gitattributes '/.claude/skills/** linguist-generated=true'
  fi

  if has_target cursor; then
    ensure_line .gitattributes '/.cursor/hooks.json linguist-generated=true'
    ensure_line .gitattributes '/.cursor/rules/** linguist-generated=true'
  fi

  if has_target copilot; then
    ensure_line .gitattributes '/.github/instructions/** linguist-generated=true'
  fi
}

has_super_linter() {
  [ -f .github/super-linter.env ] && return 0
  [ -d .github/workflows ] || return 1

  local file
  for file in .github/workflows/*.yml .github/workflows/*.yaml; do
    [ -f "$file" ] || continue
    grep -Eq 'super-linter/super-linter|github/super-linter' "$file" && return 0
  done

  return 1
}

update_super_linter() {
  has_super_linter || return 0

  mkdir -p .github

  local regex
  regex='(^|/)(\.agents/|\.codex/'
  regex="${regex}|\.claude/(apm-hooks\.json|settings\.json|rules/|skills/)"
  regex="${regex}|\.cursor/(hooks\.json|rules/)"
  if has_target copilot; then
    regex="${regex}|\.github/instructions/"
  fi
  regex="${regex})"

  local file=".github/super-linter.env"
  local tmp
  tmp="$(make_tmp_file)"

  if [ -f "$file" ] && grep -q '^FILTER_REGEX_EXCLUDE=' "$file"; then
    local line
    while IFS= read -r line || [ -n "$line" ]; do
      case "$line" in
        FILTER_REGEX_EXCLUDE=*)
          if [[ "$line" == *'.agents/'* ]]; then
            printf '%s\n' "$line" >> "$tmp"
          else
            printf '%s|%s\n' "$line" "$regex" >> "$tmp"
          fi
          ;;
        *)
          printf '%s\n' "$line" >> "$tmp"
          ;;
      esac
    done < "$file"
  else
    [ -f "$file" ] && cat "$file" > "$tmp"
    [ -s "$tmp" ] && printf '\n' >> "$tmp"
    printf 'FILTER_REGEX_EXCLUDE=%s\n' "$regex" >> "$tmp"
  fi

  mv "$tmp" "$file"
}

initialize_apm_project
update_targets
update_gitattributes
update_super_linter

echo "Configured APM agent support for targets: $TARGETS"
