#!/usr/bin/env bash
set -euo pipefail

TARGETS="claude,codex,cursor"

usage() {
  cat <<'USAGE'
Usage: configure-apm-agent-support.sh [--targets claude,codex,cursor]

Updates repository-local configuration for generated APM install assets:
- initializes apm.yml when the repository does not have one;
- ensures apm.yml contains the requested targets;
- marks generated agent assets as linguist-generated in .gitattributes;
- excludes generated agent assets from Super-Linter through FILTER_REGEX_EXCLUDE.

Add copilot only when the repository intentionally commits GitHub Copilot
instructions generated by APM.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --targets)
      TARGETS="${2:-}"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [ -z "$TARGETS" ]; then
  echo "--targets must not be empty" >&2
  exit 2
fi

IFS=',' read -r -a TARGET_ARRAY <<< "$TARGETS"
for target in "${TARGET_ARRAY[@]}"; do
  case "$target" in
    claude|codex|cursor|copilot|gemini|opencode|antigravity) ;;
    intellij|kiro|vscode|windsurf) ;;
    *)
      echo "Unsupported target: $target" >&2
      exit 2
      ;;
  esac
done

has_target() {
  local needle="$1"
  local target
  for target in "${TARGET_ARRAY[@]}"; do
    [ "$target" = "$needle" ] && return 0
  done
  return 1
}

ensure_line() {
  local file="$1"
  local line="$2"
  touch "$file"
  grep -Fxq "$line" "$file" || printf '%s\n' "$line" >> "$file"
}

initialize_apm_project() {
  if [ -f apm.yml ]; then
    return 0
  fi

  command -v apm >/dev/null 2>&1 || {
    echo "apm CLI is required to initialize apm.yml" >&2
    exit 1
  }

  apm init -y --target "$TARGETS"
}

update_targets() {
  local tmp
  tmp="$(mktemp)"

  if [ -f apm.yml ]; then
    awk '
      BEGIN { skip = 0 }
      /^# Which agent platforms to deploy to\./ { next }
      /^# Resolution order: --target flag > this field > auto-detect from filesystem\./ { next }
      /^# Accepted values:/ { next }
      /^# gemini, antigravity,/ { next }
      /^[^[:space:]#][^:]*:/ {
        if ($0 ~ /^targets:[[:space:]]*$/) {
          skip = 1
          next
        }
        skip = 0
      }
      skip == 0 { print }
    ' apm.yml > "$tmp"
  fi

  while [ -s "$tmp" ] && [ "$(tail -c 1 "$tmp")" != "" ]; do
    printf '\n' >> "$tmp"
  done

  if [ -s "$tmp" ]; then
    printf '\n' >> "$tmp"
  fi
  printf 'targets:\n' >> "$tmp"
  for target in "${TARGET_ARRAY[@]}"; do
    printf '  - %s\n' "$target" >> "$tmp"
  done

  mv "$tmp" apm.yml
}

update_gitattributes() {
  ensure_line .gitattributes '/.agents/** linguist-generated=true'

  if has_target codex; then
    ensure_line .gitattributes '/.codex/** linguist-generated=true'
  fi

  if has_target claude; then
    ensure_line .gitattributes '/.claude/apm-hooks.json linguist-generated=true'
    ensure_line .gitattributes '/.claude/settings.json linguist-generated=true'
    ensure_line .gitattributes '/.claude/rules/** linguist-generated=true'
    ensure_line .gitattributes '/.claude/skills/** linguist-generated=true'
  fi

  if has_target cursor; then
    ensure_line .gitattributes '/.cursor/hooks.json linguist-generated=true'
    ensure_line .gitattributes '/.cursor/rules/** linguist-generated=true'
  fi

  if has_target copilot; then
    ensure_line .gitattributes '/.github/instructions/** linguist-generated=true'
  fi
}

update_super_linter() {
  [ -d .github ] || [ -f .github/super-linter.env ] || return 0

  mkdir -p .github

  local regex
  regex='(^|/)(\.agents/|\.codex/'
  regex="${regex}|\.claude/(apm-hooks\.json|settings\.json|rules/|skills/)"
  regex="${regex}|\.cursor/(hooks\.json|rules/)"
  if has_target copilot; then
    regex="${regex}|\.github/instructions/"
  fi
  regex="${regex})"

  local file=".github/super-linter.env"
  local tmp
  tmp="$(mktemp)"

  if [ -f "$file" ] && grep -q '^FILTER_REGEX_EXCLUDE=' "$file"; then
    awk -v regex="$regex" '
      BEGIN { updated = 0 }
      /^FILTER_REGEX_EXCLUDE=/ {
        if ($0 !~ /\\.agents\\//) {
          print $0 "|" regex
        } else {
          print
        }
        updated = 1
        next
      }
      { print }
      END {
        if (updated == 0) {
          print "FILTER_REGEX_EXCLUDE=" regex
        }
      }
    ' "$file" > "$tmp"
  else
    [ -f "$file" ] && cat "$file" > "$tmp"
    [ -s "$tmp" ] && printf '\n' >> "$tmp"
    printf 'FILTER_REGEX_EXCLUDE=%s\n' "$regex" >> "$tmp"
  fi

  mv "$tmp" "$file"
}

initialize_apm_project
update_targets
update_gitattributes
update_super_linter

echo "Configured APM agent support for targets: $TARGETS"
