{
 "title": "Graylog (VM)",
 "tags": [
  "graylog",
  "vm"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(gl_input_throughput,cluster)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(gl_input_throughput{cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(gl_input_throughput{cluster=\"$cluster\", instance=\"$host\"},node)"
    }
   },
   {
    "name": "quantile",
    "query": {
     "query": "label_values(gl_buffer_process_time{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"},quantile)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Graylog Status",
   "type": "stat",
   "description": "Shows if Graylog service is ready",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\", instance=\"$host\", job=~\".*graylog.*\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input",
   "type": "stat",
   "description": "Show Graylog input messages per second",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gl_input_throughput{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output",
   "type": "stat",
   "description": "Show Graylog output messages per second (writed to OenSearch/ElasticSearch)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gl_output_throughput{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input buffer usage",
   "type": "stat",
   "description": "How many messages are stored in the Graylog input buffer ",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_buffer_usage{cluster=\"$cluster\", instance=\"$host\", node=\"$node\", type=\"input\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process buffer usage",
   "type": "stat",
   "description": "How many messages are stored in the Graylog process buffer ",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_buffer_usage{cluster=\"$cluster\", instance=\"$host\", node=\"$node\", type=\"process\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output buffer usage",
   "type": "stat",
   "description": "How many messages are stored in the Graylog output buffer ",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_buffer_usage{cluster=\"$cluster\", instance=\"$host\", node=\"$node\", type=\"output\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Journal append rate",
   "type": "stat",
   "description": "Show Graylog journal utilization. Graylog use journal as temporally storage of received messages which have not yet been processed by ElastiSearch.\nHigh journal utilization shows that ElasticSearch cannot process the input stream fast enough.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_journal_read_1_sec_rate{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Journal utilization",
   "type": "gauge",
   "description": "Show Graylog journal utilization. Graylog use journal as temporally storage of received messages which have not yet been processed by ElastiSearch.\nHigh journal utilization shows that ElasticSearch cannot process the input stream fast enough.",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_journal_utilization_ratio{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "gauge",
   "description": "Shows the heap JVM memory  used volume",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{cluster=\"$cluster\", instance=\"$host\", area=\"heap\"} / jvm_memory_bytes_max{cluster=\"$cluster\", instance=\"$host\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate, 5m",
   "type": "stat",
   "description": "Show total errors messages (for all log levels)  which occurs in Graylog itself.",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gl_log_appenders_total{cluster=\"$cluster\", instance=\"$host\", status=\"error\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Input / Output throughput",
   "type": "timeseries",
   "description": "Show Graylog throughput. How much does Graylog process messages from Fluentd to OpenSearh/ElasticSearch.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(gl_input_throughput{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "input"
    },
    {
     "expr": "rate(gl_output_throughput{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Throughput correlation",
   "type": "timeseries",
   "description": "Show the difference between input and output message count.\n* `Green` values mean Graylog processes and reduces the messages in buffers.\n* `Red` values mean Graylog adds messages in buffers.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(gl_output_throughput{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m]) - rate(gl_input_throughput{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "correlation"
    }
   ]
  },
  { "title": "Journald", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Journald utilization, %",
   "type": "timeseries",
   "description": "Show Graylog journal utilization. Graylog uses the journal as temporally storage of received messages that have not yet been processed by ElastiSearch.\nHigh journal utilization shows that OpenSeach/ElasticSearch cannot process the input stream fast enough.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gl_journal_utilization_ratio{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Empty messages",
   "type": "timeseries",
   "description": "Number of empty messages received by Graylog inputs.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "gl_input_empty_messages{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open conections",
   "type": "timeseries",
   "description": "Number of open connections to Graylog inputs.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_input_open_connections{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{ input_type }}"
    }
   ]
  },
  {
   "title": "Raw size, rate 30s",
   "type": "timeseries",
   "description": "Rate of raw data size received by Graylog inputs per second over the last 2 minutes.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(gl_input_raw_size_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "Raw: {{ input_type }}"
    },
    {
     "expr": "rate(gl_input_read_bytes_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "Read: {{ input_type }}"
    }
   ]
  },
  {
   "title": "Read bytes, sec",
   "type": "timeseries",
   "description": "Number of bytes read per second by Graylog inputs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_input_read_bytes_one_sec{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{ input_type }}"
    }
   ]
  },
  {
   "title": "Input traffic",
   "type": "timeseries",
   "description": "Rate of incoming traffic to Graylog inputs over the last 2 minutes.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(gl_traffic_input{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor threads",
   "type": "timeseries",
   "description": "Number of active executor threads handling Graylog input processing.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_input_launcher_executor_thread_count{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gl_input_launcher_executor_thread_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pipelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Pipeline cache hit rate",
   "type": "timeseries",
   "description": "Pipeline cache hit rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "rate(gl_pipeline_interpreter_cache_misses{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "misses"
    },
    {
     "expr": "rate(gl_pipeline_interpreter_cache_hits{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(gl_pipeline_interpreter_cache_requests{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "requests"
    },
    {
     "expr": "rate(gl_pipeline_interpreter_cache_evictions{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "evictions"
    }
   ]
  },
  {
   "title": "Pipeline cache hit rate",
   "type": "timeseries",
   "description": "Cache hit rate for the Graylog pipeline interpreter, indicating how often cached results are used.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "gl_pipeline_interpreter_cache_hit_rate{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "hits rate"
    },
    {
     "expr": "gl_pipeline_interpreter_cache_miss_rate{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "miss rate"
    }
   ]
  },
  {
   "title": "Pipeline execution time",
   "type": "timeseries",
   "description": "Execution time of the Graylog pipeline interpreter, measuring processing duration per request.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_pipeline_interpreter_execution_time{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Decode time",
   "type": "timeseries",
   "description": "Time taken to decode messages in the Graylog process buffer.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_process_buffer_decode_time{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parse time",
   "type": "timeseries",
   "description": "Time taken to parse messages in the Graylog process buffer.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_process_buffer_parse_time{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtered messages, count",
   "type": "timeseries",
   "description": "Rate of messages filtered out by the Graylog process buffer over the last 2 minutes.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(gl_process_buffer_filtered_messages_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing messages, count",
   "type": "timeseries",
   "description": "Rate of messages successfully processed and sent from the Graylog process buffer over the last 2 minutes.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(gl_process_buffer_outgoing_messages_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process threads, count",
   "type": "timeseries",
   "description": "Number of threads created by the Graylog process buffer thread factory for message processing.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_process_buffer_thread_factory{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Buffer sizes, by type",
   "type": "stat",
   "description": "Buffer sizes, by type",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_buffer_size{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Buffer usage, by type ",
   "type": "timeseries",
   "description": "Represents the current utilization percentage of the Graylog message processing buffer.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "gl_buffer_usage{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Buffer process time, by type ",
   "type": "timeseries",
   "description": "Represents the time taken to process messages in the Graylog buffer at a specific quantile.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_buffer_process_time{cluster=\"$cluster\", instance=\"$host\", node=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "{{ type }}: {{ quantile }}"
    }
   ]
  },
  {
   "title": "Buffer process incoming messages, by type ",
   "type": "timeseries",
   "description": "Represents the rate of incoming messages processed by the Graylog buffer over the last 2 minutes.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(gl_buffer_processor_incoming_messages_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Buffer raw message encoder handler incoming messages, by type ",
   "type": "timeseries",
   "description": "Represents the rate of incoming messages handled by the raw message encoder in Graylog over the last 2 minutes.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(gl_buffer_raw_message_encoder_handler_incoming_messages_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Incoming messages, per stream",
   "type": "timeseries",
   "description": "Represents the rate of incoming messages processed by Graylog streams over the last 2 minutes.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "rate(gl_stream_incoming_messages_total[2m])",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Stream rules execution time",
   "type": "timeseries",
   "description": "Measures the execution time of Graylog stream rules at different quantiles, helping to analyze rule processing performance.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_stream_rules_execution_time{cluster=\"$cluster\", instance=\"$host\", node=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "Stream: {{ stream }}, Rule: {{ stream_rule }}, Quantile: {{ quantile }}"
    }
   ]
  },
  {
   "title": "Router can't remove default",
   "type": "timeseries",
   "description": "Indicates the number of attempts to remove the default stream in Graylog, which is not allowed.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_stream_router_cannot_remove_default{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Indexer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "Searches, Ranges, Requests",
   "type": "timeseries",
   "description": "Represents the number of search requests sent from Graylog to Elasticsearch.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "targets": [
    {
     "expr": "gl_indexer_search_elasticsearch_requests{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gl-gl_indexer_search_elasticsearch_searches{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gl_indexer_search_elasticsearch_ranges{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid timestamps",
   "type": "timeseries",
   "description": "Counts the total number of messages with invalid timestamps encountered by the Graylog indexer.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "targets": [
    {
     "expr": "gl_indexer_message_invalid_timestamps_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Field type poller time",
   "type": "timeseries",
   "description": "Measures the time taken by the Graylog indexer field type poller to complete its execution.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_indexer_field_type_poller_time{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  { "title": "Event bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 } },
  {
   "title": "Scheduler system posts",
   "type": "timeseries",
   "description": "Counts the number of system event posts scheduled by the Graylog event bus job scheduler.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 166 },
   "targets": [
    {
     "expr": "gl_event_bus_job_scheduler_system_posts{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Scheduler system registrations",
   "type": "timeseries",
   "description": "Tracks the number of system event registrations in the Graylog event bus job scheduler.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 166 },
   "targets": [
    {
     "expr": "gl_event_bus_job_scheduler_system_registrations{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler system registrations",
   "type": "timeseries",
   "description": "Measures the idle time of the executor service in the Graylog event bus provider.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 176 },
   "targets": [
    {
     "expr": "gl_event_bus_provider_executor_service_idle{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gl_event_bus_provider_executor_service_duration{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenSearch/ElasticSearch output",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 }
  },
  {
   "title": "Output processing time",
   "type": "timeseries",
   "description": "Measures the processing time of blocking Elasticsearch output operations in Graylog.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_blocking_elasticsearch_output_process_time{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Output flushes",
   "type": "timeseries",
   "description": "Tracks the rate of buffer flushes in the blocking Elasticsearch output over a specified window.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(gl_blocking_elasticsearch_output_buffer_flushes_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(gl_blocking_elasticsearch_output_buffer_flushes_requested_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "Requested flushes"
    },
    {
     "expr": "rate(gl_blocking_elasticsearch_output_buffer_flush_failures_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "Failures flushes"
    }
   ]
  },
  {
   "title": "Output batch size",
   "type": "timeseries",
   "description": "Represents the batch size of messages processed by the blocking Elasticsearch output.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_blocking_elasticsearch_output_batch_size{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Writes and Failuers",
   "type": "timeseries",
   "description": "Represents the rate of failed Elasticsearch output operations over the last specified minutes.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(gl_elasticsearch_output_failures_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "Failures"
    },
    {
     "expr": "rate(gl_elasticsearch_output_writes_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "Writes"
    }
   ]
  },
  { "title": "Failure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 } },
  {
   "title": "Failure consumed and submitted",
   "type": "timeseries",
   "description": "Represents the total number of failures consumed from the failure queue for the specified cluster, instance, and node.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
   "targets": [
    {
     "expr": "gl_failure_queue_consumed_failures_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gl_failure_queue_submitted_failures_total{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure queue size",
   "type": "timeseries",
   "description": "Represents the current size of the failure queue, indicating the number of failed messages waiting to be processed for the specified cluster, instance, and node.\n\n\n\n\n\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
   "targets": [
    {
     "expr": "gl_failure_queue_size{cluster=\"$cluster\", instance=\"$host\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}