{
 "title": "JVM Processes",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "tags": [
  "process",
  "java"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"},container)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{area=\"heap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{area=\"nonheap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"},id)"
    }
   },
   {
    "name": "server_uri",
    "label": "Server URI",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, uri)"
    }
   },
   {
    "name": "client_uri",
    "label": "Client URI",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, uri)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM Processes Help",
     "type": "text",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 185 },
     "options": {
      "content": "This dashboard designed to show statistic about any Java processes.\r\n\r\nAlmost all metrics collected from any Java process with using [Micrometer](http://micrometer.io/) which [Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics) and [Quarkus](https://quarkus.io/guides/micrometer) recommended to ue for instrumetation in official documents.\r\n\r\nTo view metrics about Java processes within different pods, you can use the variables at the top of the page and switch between different namespaces and pods and containers into them. Variables allow to choose only those namespaces, pods, contains for which Prometheus collected metrics. By choosing a namespace, you filter the pod list by selected namespace. A similar filter is applied to the variable with container name. List of namespaces, pods, containers selected from metric `jvm_memory_used_bytes`.\r\n\r\nPlease rememeber that this dashboard can't show correctly metrics which were collected by [JXM Exporter](https://github.com/prometheus/jmx_exporter)."
     }
    }
   ]
  },
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Shows time from VM start",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "Shows VM start time",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} * 1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "description": "Shows memory used by heap",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-heap used",
   "type": "stat",
   "description": "Shows memory used by non-heap",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "description": "Shows the heap JVM memory  used volume",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"heap\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "description": "Shows the non-heap JVM memory  used volume",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"nonheap\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "description": "Shows the amount of memory \n - used\n - committed to use\n -  max that can be used",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "timeseries",
   "description": "Shows process_memory_vss_bytes",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_vss_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
     "legendFormat": "vss"
    },
    {
     "expr": "process_memory_rss_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_swap_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_rss_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} + process_memory_swap_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Shows system CPU usage,  process CPU usage and average process CPU usage",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Load",
     "type": "timeseries",
     "description": "Shows\n - the sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time\n - the number of processors available to the Java virtual machine\n\n",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "system-1m"
      },
      {
       "expr": "system_cpu_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "cpus"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "Shows\n - the current number of live threads including both daemon and non-daemon threads\n - the current number of live daemon threads\n - the peak live thread count since the Java virtual machine started or peak was reset\n -  the process threads",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "description": "Shows the current number of threads having NEW state\n",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Log Events",
     "type": "timeseries",
     "description": "Show increase of log events",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "increase(logback_events_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "description": "Show amount of processed files\n - open\n - max that can be open",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_files_open_files{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max_files{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "timeseries",
     "description": "Shows amount of space\n - used\n - commited to be used\n - max available for use",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "repeat": "jvm_memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "timeseries",
     "description": "Shows amount of space\n - used\n - commited to be used\n - max available for use",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
     "repeat": "jvm_memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Server Requests Rate",
     "type": "timeseries",
     "description": "Shows per-second rate of HTTP server requests count",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", uri=~\"$server_uri\"}[2m])) by (uri, method)",
       "legendFormat": "{{ uri }} - {{ method }}"
      }
     ]
    },
    {
     "title": "HTTP Server Errors Rate",
     "type": "timeseries",
     "description": "Shows the count of HTTP server errors",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status=~\"4..\", uri=~\"$server_uri\"}[2m])) by (uri, method) OR on() vector(0)",
       "legendFormat": "{{ uri }} - {{ method }} - 4xx"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status=~\"5..\", uri=~\"$server_uri\"}[2m])) by (uri, method) OR on() vector(0)",
       "legendFormat": "{{ uri }} - {{ method }} - 5xx"
      }
     ]
    },
    {
     "title": "Duration Server Request",
     "type": "timeseries",
     "description": "Shows per-second rate of the average time per server request",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status!~\"5..\", uri=~\"$server_uri\"}[2m])) by (uri, method) / sum(rate(http_server_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status!~\"5..\", uri=~\"$server_uri\"}[2m])) by (uri, method)",
       "legendFormat": "{{ uri }} - {{ method }}- AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status!~\"5..\", uri=~\"$server_uri\"}) by (uri, method)",
       "legendFormat": "{{ uri }} - {{ method }} - MAX"
      }
     ]
    },
    {
     "title": "HTTP Client Requests Rate",
     "type": "timeseries",
     "description": "Shows per-second rate of  HTTP Client requests count",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", uri=~\"$client_uri\"}[2m])) by (uri, method)",
       "legendFormat": "{{ uri }} - {{ method }}"
      }
     ]
    },
    {
     "title": "HTTP Client Errors Rate",
     "type": "timeseries",
     "description": "Shows the count of HTTP Client errors",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status=~\"4..\", uri=~\"$client_uri\"}[2m])) by (uri, method) OR on() vector(0)",
       "legendFormat": "{{ uri }} - {{ method }} - 4xx"
      },
      {
       "expr": "sum(rate(http_client_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status=~\"5..\", uri=~\"$client_uri\"}[2m])) by (uri, method) OR on() vector(0)",
       "legendFormat": "{{ uri }} - {{ method }} - 5xx"
      }
     ]
    },
    {
     "title": "Duration Client Request",
     "type": "timeseries",
     "description": "Shows per-second rate of the average time per client request",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status!~\"5..\", uri=~\"$client_uri\"}[2m])) by (uri, method) / sum(rate(http_client_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status!~\"5..\", uri=~\"$client_uri\"}[2m])) by (uri, method)",
       "legendFormat": "{{ uri }} - {{ method }} - AVG"
      },
      {
       "expr": "max(http_client_requests_seconds_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", status!~\"5..\", uri=~\"$client_uri\"}) by (uri, method)",
       "legendFormat": "{{ uri }} - {{ method }} - MAX"
      }
     ]
    },
    {
     "title": "Spring: HTTP Connections Pool",
     "type": "timeseries",
     "description": "Shows Tomcat and Jetty\n - busy thereads\n - current threads\n - max threads",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_threads_busy_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "TOMCAT - BSY"
      },
      {
       "expr": "tomcat_threads_current_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "TOMCAT - CUR"
      },
      {
       "expr": "tomcat_threads_config_max_threads{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "TOMCAT - MAX"
      },
      {
       "expr": "jetty_threads_busy{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "JETTY - BSY"
      },
      {
       "expr": "jetty_threads_current{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "JETTY - CUR"
      },
      {
       "expr": "jetty_threads_config_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "JETTY - MAX"
      }
     ]
    },
    {
     "title": "Quarkus: HTTP Server Worker Pool",
     "type": "timeseries",
     "description": "Shows connections pool for Quarkus applications",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum(worker_pool_active{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (pool_name) OR on() vector(0)",
       "legendFormat": "Active: {{pool_name}} pool"
      },
      {
       "expr": "sum(worker_pool_idle{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (pool_name) OR on() vector(0)",
       "legendFormat": "Idle: {{pool_name}} pool"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Statistics (Quarkus)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC Server Requests Received / Responses Sent",
     "type": "timeseries",
     "description": "Shows per-second rate of gRPC Server received requests and responses sent count",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(grpc_server_requests_received_messages_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (service,method) OR on() vector(0)",
       "legendFormat": "Recieved: {{service}}/{{method}}"
      },
      {
       "expr": "sum(irate(grpc_server_responses_sent_messages_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (service,method) OR on() vector(0)",
       "legendFormat": "Sent: {{service}}/{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Server Unary Call Error Rate",
     "type": "timeseries",
     "description": "Shows the count of gRPC Server errors",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_processing_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", methodType=\"UNARY\", statusCode!=\"OK\"}[$interval])) by (service, method, statusCode) OR on() vector(0)",
       "legendFormat": "{{statusCode}}: {{service}}/{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Server Average Unary Call Processing Duration",
     "type": "timeseries",
     "description": "Shows per-second rate of the average time of gRPC call processing by server",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_processing_duration_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", methodType=\"UNARY\"}[$interval])) by (service, method) / sum(rate(grpc_server_processing_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", methodType=\"UNARY\"}[$interval])) by (service, method)",
       "legendFormat": "{{service}}/{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Client Responses Received / Requests Sent",
     "type": "timeseries",
     "description": "Shows per-second rate of gRPC Server received responses and sent requests count",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(grpc_client_responses_received_messages_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (service,method) OR on() vector(0)",
       "legendFormat": "Recieved: {{service}}/{{method}}"
      },
      {
       "expr": "sum(irate(grpc_client_requests_sent_messages_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (service,method) OR on() vector(0)",
       "legendFormat": "Sent: {{service}}/{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Client Unary Call Error Rate",
     "type": "timeseries",
     "description": "Shows the count of gRPC Client errors",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_processing_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", methodType=\"UNARY\", statusCode!=\"OK\"}[$interval])) by (service, method, statusCode) OR on() vector(0)",
       "legendFormat": "{{statusCode}}: {{service}}/{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Client Average Unary Call Processing Duration",
     "type": "timeseries",
     "description": "Shows per-second rate of the average time of gRPC call processing by client",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_processing_duration_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", methodType=\"UNARY\"}[$interval])) by (service, method) / sum(rate(grpc_client_processing_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", methodType=\"UNARY\"}[$interval])) by (service, method)",
       "legendFormat": "{{service}}/{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Statistics (Spring)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC Server Unary Requests by OK Code",
     "type": "timeseries",
     "description": "Shows amount of successful requests to different methods per second for gRPC Server",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"UNARY\", grpc_code=\"OK\"}[$interval])) by (grpc_code, grpc_method, grpc_service)",
       "legendFormat": "{{grpc_code}}:{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "gRPC Server Unary Failed Requests",
     "type": "timeseries",
     "description": "Shows amount of error requests to different methods per second partitioned by error codes",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"UNARY\", grpc_code!=\"OK\"}[$interval])) by (grpc_code, grpc_method, grpc_service) OR on() vector(0)",
       "legendFormat": "{{grpc_code}}:{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "gRPC Server 95%-tile Latency of Unary Response Time",
     "type": "timeseries",
     "description": "How long it took to process an unary request, partitioned by method",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \r\n  sum(rate(grpc_server_handled_latency_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"UNARY\"}[$interval])) by (grpc_service,grpc_method,le)\r\n) * 1000 OR on() vector(0)",
       "legendFormat": "{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "gRPC Client Unary Requests by OK Code",
     "type": "timeseries",
     "description": "Shows amount of successful requests to different methods per second for gRPC Client",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_completed_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"UNARY\", grpc_code=\"OK\"}[$interval])) by (grpc_code, grpc_method, grpc_service)",
       "legendFormat": "{{grpc_code}}:{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "gRPC Client Unary Failed Requests",
     "type": "timeseries",
     "description": "Shows amount of error requests to different methods per second partitioned by error codes for gRPC Client",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_completed_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"UNARY\", grpc_code!=\"OK\"}[$interval])) by (grpc_code, grpc_method, grpc_service) OR on() vector(0)",
       "legendFormat": "{{grpc_code}}:{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "gRPC Client 95%-tile Latency of Unary Response Time",
     "type": "timeseries",
     "description": "How long it took to process an unary request, partitioned by method for gRPC Client",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \r\n  sum(rate(grpc_client_completed_latency_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\",grpc_type=\"UNARY\"}[$interval])) by (grpc_service,grpc_method,le)\r\n) * 1000 OR on() vector(0)",
       "legendFormat": "{{grpc_service}}/{{ grpc_method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collections",
     "type": "timeseries",
     "description": "Shows per-second rate of GC pause increase",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "timeseries",
     "description": "Shows per-second rate of average increasing pause time per  pause count",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])/rate(jvm_gc_pause_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "timeseries",
     "description": "Shows per-second rate of increasing memory allocated and promouted by GC",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JDBC/Hikari",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JDBC Connections",
     "type": "timeseries",
     "description": "Show current count of JDBC connections and them limits",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jdbc_connections_active{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "Active"
      },
      {
       "expr": "jdbc_connections_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Hickari Pool: Connections",
     "type": "timeseries",
     "description": "Show count of connections via Hickari poll by statuses ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "Pending"
      },
      {
       "expr": "hikaricp_connections_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"} OR on() vector(0)",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Hickari Pool: Usage",
     "type": "timeseries",
     "description": "Show statistic of using Hickari Pool connections, by time and by connections count",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$__range]) OR on() vector(0)",
       "legendFormat": "Usage"
      },
      {
       "expr": "increase(hikaricp_connections_usage_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$__range]) OR on() vector(0)",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Agroal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Pool",
     "type": "timeseries",
     "description": "Shows connection pool for Agroal",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(agroal_active_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
       "legendFormat": "Active connections"
      },
      {
       "expr": "sum(agroal_available_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
       "legendFormat": "Idle connections, available to be acquired"
      },
      {
       "expr": "sum(agroal_invalid_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
       "legendFormat": "Connections removed from the pool for being invalid"
      },
      {
       "expr": "sum(agroal_max_used_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
       "legendFormat": "Maximum number of connections active simultaneously"
      }
     ]
    },
    {
     "title": "Created and Destroyed Connections",
     "type": "timeseries",
     "description": "Shows a number of created and destroyed connections",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(agroal_creation_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval]))",
       "legendFormat": "Created connections"
      },
      {
       "expr": "sum(increase(agroal_destroy_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval]))",
       "legendFormat": "Destroyed connections"
      }
     ]
    },
    {
     "title": "Connections Timings",
     "type": "timeseries",
     "description": "Shows average time to create connections and acquire them for Agroal",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(agroal_blocking_time_total_milliseconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval]))",
       "legendFormat": "Time to acquire a connection"
      },
      {
       "expr": "sum(rate(agroal_creation_time_total_milliseconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval]))",
       "legendFormat": "Time to create a connection"
      }
     ]
    },
    {
     "title": "Acquired Rate",
     "type": "timeseries",
     "description": "Shows acquired operations per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(agroal_acquire_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval]))",
       "legendFormat": "Acquired operations"
      }
     ]
    },
    {
     "title": "Leak Detected",
     "type": "timeseries",
     "description": "Shows number of times a leak was detected (a single connection can be detected multiple times)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(agroal_leak_detection_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval]))",
       "legendFormat": "Leak detections"
      }
     ]
    }
   ]
  },
  {
   "title": "Cassandra Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CQL Response Time",
     "type": "timeseries",
     "description": "How long Cassandra process a CQL request (average time)",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(cassandra_session_cql_requests_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session) / sum(rate(cassandra_session_cql_requests_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session)",
       "legendFormat": "Session: {{session}}"
      }
     ]
    },
    {
     "title": "95%-tile Latency of CQL Response Time",
     "type": "timeseries",
     "description": "How long Cassandra process a CQL request (95th percentile)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \r\n  sum(rate(cassandra_session_cql_requests_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session, le)\r\n)",
       "legendFormat": "Session: {{session}}"
      }
     ]
    },
    {
     "title": "99%-tile Latency of CQL Response Time",
     "type": "timeseries",
     "description": "How long Cassandra process a CQL request (99th percentile)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \r\n  sum(rate(cassandra_session_cql_requests_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session, le)\r\n)",
       "legendFormat": "Session: {{session}}"
      }
     ]
    },
    {
     "title": "Receive/Sent Data",
     "type": "timeseries",
     "description": "Shows network traffic in bytes per second for Cassandra sessions",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(cassandra_session_bytes_received_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session)",
       "legendFormat": "Received: Session: {{session}}"
      },
      {
       "expr": "sum(irate(cassandra_session_bytes_sent_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session)",
       "legendFormat": "Sent: Session: {{session}}"
      }
     ]
    },
    {
     "title": "CQL Timeouts Rate",
     "type": "timeseries",
     "description": "Shows count of CQL timeouts",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(cassandra_session_cql_client_timeouts_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session) OR on() vector(0)",
       "legendFormat": "Session: {{session}}"
      }
     ]
    },
    {
     "title": "CQL Request Errors Rate",
     "type": "timeseries",
     "description": "Shows count of errors during CQL requests",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(cassandra_nodes_errors_request_write_timeouts_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session, node) OR on() vector(0)",
       "legendFormat": "Write timeouts: Node: {{node}} Session: {{session}}"
      },
      {
       "expr": "sum(rate(cassandra_nodes_errors_request_read_timeouts_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session, node) OR on() vector(0)",
       "legendFormat": "Read timeouts: Node: {{node}} Session: {{session}}"
      },
      {
       "expr": "sum(rate(cassandra_nodes_errors_request_unavailables_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session, node) OR on() vector(0)",
       "legendFormat": "Unavailables: Node: {{node}} Session: {{session}}"
      },
      {
       "expr": "sum(rate(cassandra_nodes_errors_request_others_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session, node) OR on() vector(0)",
       "legendFormat": "Others: Node: {{node}} Session: {{session}}"
      }
     ]
    },
    {
     "title": "Connection Errors Rate",
     "type": "timeseries",
     "description": "Shows count of errors during connection to Cassandra",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(cassandra_nodes_errors_connection_init_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session, node) OR on() vector(0)",
       "legendFormat": "Init: Node: {{node}} Session: {{session}}"
      },
      {
       "expr": "sum(rate(cassandra_nodes_errors_connection_auth_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session, node) OR on() vector(0)",
       "legendFormat": "Auth: Node: {{node}} Session: {{session}}"
      }
     ]
    },
    {
     "title": "Throttling Errors Rate",
     "type": "timeseries",
     "description": "Shows count of throttling errors",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(cassandra_session_throttling_errors_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (session) OR on() vector(0)",
       "legendFormat": "Session: {{session}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "stat",
     "description": "Shows number of current connections from the service to RabbitMQ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_connections{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Channels",
     "type": "stat",
     "description": "Shows number of current RabbitMQ channels",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_channels{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Published Messages Rate",
     "type": "timeseries",
     "description": "Shows per-second rate of published messages",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_published_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Acknowledged Messages Rate",
     "type": "timeseries",
     "description": "Shows per-second rate of acknowledged messages",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_acknowledged_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Unrouted Published Messages Rate",
     "type": "timeseries",
     "description": "Shows per-second rate of unrouted published messages",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_unrouted_published_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Unacknowledged Published Messages Rate",
     "type": "timeseries",
     "description": "Shows per-second rate of unacknowledged published messages",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_not_acknowledged_published_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Acknowledged Published Messages Rate",
     "type": "timeseries",
     "description": "Shows per-second rate of acknowledged published messages",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_acknowledged_published_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Consumed Messages Rate",
     "type": "timeseries",
     "description": "Shows per-second rate of consumed messages",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_consumed_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Failed to Publish Messages Rate",
     "type": "timeseries",
     "description": "Shows per-second rate of failed to publish messages",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_failed_to_publish_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Rejected Messages Rate",
     "type": "timeseries",
     "description": "Shows per-second rate of rejected messages",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_rejected_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "description": "Shows count of classes loaded by class loader",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta",
     "type": "timeseries",
     "description": "Shows delta of loaded classes count ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[2m])",
       "legendFormat": "delta-1m"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Direct Buffers Size",
     "type": "timeseries",
     "description": "Shows buffer size\n - used\n - total available",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers Count",
     "type": "timeseries",
     "description": "Shows estimation of the number of buffers in the pool",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers Size",
     "type": "timeseries",
     "description": "Shows estimation of \n - the memory that the Java virtual machine is using for this buffer pool\n - capacity of the buffers in this pool",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers Count",
     "type": "timeseries",
     "description": "Shows estimation of the number of buffers in the pool",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  }
 ]
}